/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniqq_MainActivity */
#include <fmod.hpp>//fmod 的头文件
#include <string>
#ifndef _Included_com_example_jniqq_MainActivity
#define _Included_com_example_jniqq_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_jniqq_MainActivity_MODEL_NORMAL
#define com_example_jniqq_MainActivity_MODEL_NORMAL 0L
#undef com_example_jniqq_MainActivity_MODEL_LUOLI
#define com_example_jniqq_MainActivity_MODEL_LUOLI 1L
#undef com_example_jniqq_MainActivity_MODEL_DASHU
#define com_example_jniqq_MainActivity_MODEL_DASHU 2L
#undef com_example_jniqq_MainActivity_MODEL_GAOGUAI
#define com_example_jniqq_MainActivity_MODEL_GAOGUAI 3L
#define com_example_jniqq_mainactivity_model_XIAOHUANGREN 4L
#define com_example_jniqq_mainactivity_model_KONGLING 5L
#define com_example_jniqq_mainactivity_model_JINGSONG 6L
/*
 * Class:     com_example_jniqq_MainActivity
 * Method:    change
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jniqq_MainActivity_voiceChange
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif

//线程
extern "C"
JNIEXPORT void JNICALL
Java_com_example_jniqq_MainActivity_nativeThread(JNIEnv *env, jobject thiz);